add solution task5
js-tasks-ru/htmlcss-20220616_zero713 pull request #6
Opened 2022-06-26 19:34 UTC by VladBelov1

2022-06-27 09:36 UTC, GSemikozov requested changes

2022-06-27 09:36 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
высоту не стоит ограничивать

2022-06-27 09:36 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 0.8px;
1px

2022-06-27 09:36 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__bottom-part {
свойство можно перенести в .histogram__chart а элемент .histogram__bottom-part удалить

2022-06-27 09:36 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__margins {
лучше обнулять сразу конкретным элементам

2022-06-27 10:49 UTC, VladBelov1 commented on 04-lection2/01-histogram/histogram.css
> +    gap: 0.8px;
При 1px почему-то между некоторыми блоками расстояние 2px, поэтому поставил 0.8.

2022-06-27 10:51 UTC, VladBelov1 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__bottom-part {
тут все понятно

2022-06-27 10:54 UTC, VladBelov1 commented on 04-lection2/01-histogram/histogram.css
> +    height: 185px;
тут все ясно, установил высоту блока через внутренний gap

2022-06-27 10:56 UTC, VladBelov1 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__margins {
ясно

2022-06-27 14:39 UTC, GSemikozov requested changes

2022-06-27 14:39 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__font-family {
вот это все на самом деле тоже можно перенести сразу в .histogram

2022-06-27 21:13 UTC, VladBelov1 commented on 04-lection2/01-histogram/histogram.css
> +.histogram__font-family {
Сделано.

2022-06-28 19:19 UTC, GSemikozov approved these changes

2022-06-28 19:20 UTC, merged