Task6 skeleton
js-tasks-ru/htmlcss-20220616_zero713 pull request #7
Opened 2022-06-27 11:51 UTC by VladBelov1

2022-06-27 11:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-27 14:43 UTC, GSemikozov requested changes

2022-06-27 14:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 579px;
лишнее, блок будет растягиваться по родителю

2022-06-27 14:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-top: 8px;
сразу на .skeleton__rows

2022-06-27 14:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__row_top-row1 {
очень декларативные модификаторы, их нельзя будет переиспользовать (что если линии которая сейчас top-row1, в дальнейшем будет использоваться ниже но уже в положении bottom-row2? придется дублировать стили). Плюс модификаторам задаем емкое имя по тому ЧТО / КАК он модифицирует, то есть здесь:  .skeleton__row_short, .skeleton__row_long etc (модифицируем ширину).

2022-06-27 14:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
ширину лучше в процентах, чтобы привязка была к размеру родителя и сохранялись пропорции при изменении размеров родителя

2022-06-27 19:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-27 19:22 UTC, VladBelov1 commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-top: 8px;
исправлено

2022-06-27 19:22 UTC, VladBelov1 commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 579px;
исправлено

2022-06-27 19:23 UTC, VladBelov1 commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-top: 8px;
исправлено

2022-06-27 19:23 UTC, VladBelov1 commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__row_top-row1 {
понятно

2022-06-27 19:23 UTC, VladBelov1 commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
ок

2022-06-27 21:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-28 19:20 UTC, GSemikozov approved these changes

2022-06-28 19:20 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-06-28 19:23 UTC, GSemikozov approved these changes

2022-06-28 19:23 UTC, merged